### ISSUE TITLE
TypeError: tuple indices must be integers or slices, not tuple

### ISSUE THREAD

**Issue by adityamukherjee42** [abewley/sort#136]
i have been facing this issue not able to know which line please help

**Comment by InputBlackBoxOutput** [comment]
I am facing a similar issue. I speculate that the code is broken somewhere because of numpy.

Code
```
        detections = [[start_point[0], start_point[1], end_point[0], end_point[1], confidence] for (start_point, end_point, label, confidence) in results]
        # np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(100)})
        dets = np.asarray(detections)
        print(dets)
        tracks = tracker.update(dets)
```

Debug output with error:
```
[]
[]
[]
[]
[]
[]
[]
[[109.         147.         170.         173.           0.50095928]]
[[105.         141.         171.         171.           0.36380956]]
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\commits\virtual_line\run.py", line 100, in <module>
    tracks = tracker.update(dets)
  File "C:\Users\admin\Desktop\commits\virtual_line\sort.py", line 203, in update
    matched, unmatched_dets, unmatched_trks = associate_detections_to_trackers(dets,trks)
  File "C:\Users\admin\Desktop\commits\virtual_line\sort.py", line 144, in associate_detections_to_trackers
    if(d not in matched_indices[:,0]):
TypeError: tuple indices must be integers or slices, not tuple
```

@adityamukherjee42  Can you please share the portion of the code that caused the error along with debugging output?

**Comment by adityamukherjee42** [comment]
No man still trying to

**Comment by InputBlackBoxOutput** [comment]
@adityamukherjee42   Any progress on the issue?

**Comment by cocoph** [comment]
> @adityamukherjee42 Found a solution
> Use pip to install lap
> Comment out the import and use the following function.
> 
> ```python
> def linear_assignment(cost_matrix):
>   try:
>     import lap
>     _, x, y = lap.lapjv(cost_matrix, extend_cost=True)
>     return np.array([[y[i], i] for i in x if i >= 0])
>   except ImportError:
>     from scipy.optimize import linear_sum_assignment
>     x, y = linear_sum_assignment(cost_matrix)
>     return np.array(list(zip(x, y)))
> ```
> 
> I hope this helps

I'm facing the same issue, can you please explain more where to put those functions?

**Comment by InputBlackBoxOutput** [comment]
*sklearn.utils.linear_assignment_* was replaced with *scipy.optimize.linear_sum_assignment* since the latter was pruned in the current version.  I found the above function in a previous commit. 

Follows these steps to fix the bug.

1. Comment out the import 
```
# from scipy.optimize import linear_sum_assignment as linear_assignment
```
2. Use pip to install lap

3. Copy and paste the above function in the sort.py file

**Comment by cocoph** [comment]
> _sklearn.utils.linear_assignment__ was replaced with _scipy.optimize.linear_sum_assignment_ since the latter was pruned in the current version. I found the above function in a previous commit.
> 
> Follows these steps to fix the bug.
> 
> 1. Comment out the import
> 
> ```
> # from scipy.optimize import linear_sum_assignment as linear_assignment
> ```
> 
> 1. Use pip to install lap
> 2. Copy and paste the above function in the sort.py file

It's working now, many thanks

**Comment by vkavin4201** [comment]
Facing a ValueError now
33   try:
     34     import lap
---> 35     _, x, y = lap.lapjv(cost_matrix, extend_cost=True)
     36     return np.array([[y[i], i] for i in x if i >= 0])
     37   except ImportError:

lap/_lapjv.pyx in lap._lapjv.lapjv()

[/usr/local/lib/python3.7/dist-packages/numpy/core/_methods.py](https://localhost:8080/#) in _amax(a, axis, out, keepdims, initial, where)
     38 def _amax(a, axis=None, out=None, keepdims=False,
     39           initial=_NoValue, where=True):
---> 40     return umr_maximum(a, axis, None, out, keepdims, initial, where)
     41 
     42 def _amin(a, axis=None, out=None, keepdims=False,

ValueError: zero-size array to reduction operation maximum which has no identity
