### ISSUE TITLE
exception error: IndexError: list index out of range

### ISSUE THREAD

**Issue by GaoTianTian96** [abewley/sort#140]
Traceback (most recent call last):
  File "D:/work/yolact/eval.py", line 340, in prep_display
    track_bbs_ids = trakcer.update(current_dets)
  File "D:\work\yolact\sort.py", line 239, in update
    self.trackers[m[1]].update(dets[m[0], :])
IndexError: list index out of range
Traceback (most recent call last):
  File "D:/work/yolact/eval.py", line 340, in prep_display
    track_bbs_ids = trakcer.update(current_dets)
  File "D:\work\yolact\sort.py", line 228, in update
    pos = self.trackers[t].predict()[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "D:/work/yolact/eval.py", line 340, in prep_display
    track_bbs_ids = trakcer.update(current_dets)
  File "D:\work\yolact\sort.py", line 239, in update
    self.trackers[m[1]].update(dets[m[0], :])
IndexError: list index out of range

Process finished with exit code -1
-----------------------------------------------------------------------------
The data was printed without crossing the line

**Comment by ZXStudio** [comment]
I have encountered similar problems before. Thank you for your answer at @sauravns. In the iou_batch() function of sort.py, we should first check if the length of bb_test is 0, and then set the detection to an empty numpy array.

 `def iou_batch(bb_test, bb_gt):
     if len(bb_test) == 0:
          bb_test = np.empty((0, 5))`
