### ISSUE TITLE
Error in iou_batches 

### ISSUE THREAD

**Issue by daonam2202ntg** [abewley/sort#182]
I got this error while running, please help me

Traceback (most recent call last):
  File "D:\License_plate_pycharm\License_plate_project\pythonProject6\main.py", line 39, in <module>
    track_ids = mot_tracker.update(np.asarray(detections_))
  File "D:\License_plate_pycharm\License_plate_project\pythonProject6\sort\sort.py", line 233, in update
    matched, unmatched_dets, unmatched_trks = associate_detections_to_trackers(dets,trks, self.iou_threshold)
  File "D:\License_plate_pycharm\License_plate_project\pythonProject6\sort\sort.py", line 164, in associate_detections_to_trackers
    iou_matrix = iou_batch(detections, trackers)
  File "D:\License_plate_pycharm\License_plate_project\pythonProject6\sort\sort.py", line 56, in iou_batch
    yy1 = np.maximum(bb_test[..., 1], bb_gt[..., 1])
IndexError: index 1 is out of bounds for axis 1 with size 1

**Comment by PommGolden** [comment]
I had the same issue and solved it by modifying `if(len(trackers)==0):` to `if(len(trackers)==0 or len(detections)==0):` but I'm not quite sure the algorithm will still work as intended. However, I don't see any impact on the main detection algorithm in the license plate project I use too.

**Comment by bknight44** [comment]
looking at the code I think this is the correct fix. The only thing the function is doing is connecting trackers with the detections. So if there are no detections, then there will obviously be no matches. So returning the empty arrays will be fine.
