### ISSUE TITLE
Sort fails when new detection

### ISSUE THREAD

**Issue by stetiri** [abewley/sort#63]
Hi, 
I'm trying to implement sort but I'm having some issues.
1. When the tracker is working and it doen't get any new detections I got the following message.
`Traceback (most recent call last):
  File "/home/YOLOv3_TensorFlow-master/Dect_Track_SORT.py", line 131, in <module>
    tracks = tracker.update(detections)
  File "/home//YOLOv3_TensorFlow-master/sort.py", line 213, in update
    trk.update(dets[d,:][0])
IndexError: too many indices for array`

2. I have the same issue when at the begging it doesn't get any detection and a new one appear, showing the same message.

I would appreaciate any help regarding this issue, thanks.

**Comment by marfis89** [comment]
same

**Comment by khanhhoangadt** [comment]
> same

Error in data trainning for you. No object in frame

**Comment by pryanga-wk** [comment]
I agree that there will be an error thrown when there is no detections in the frame, however, in sort.py, the following line is puzzling: 
      
    "Requires: this method must be called once for each frame even with empty detections.
    Returns the a similar array, where the last column is the object ID."
So how do we pass in empty detection?

**Comment by ShahrozTanveer** [comment]
i fixed this problem by using (check)
`if len(d)>0:
    trk.update(dets[d,:][0]) 
`

**Comment by ShahrozTanveer** [comment]
i fixed this problem by using (check)
`if len(d)>0:`
`     trk.update(dets[d,:][0])`
