### ISSUE TITLE
AttributeError: 'module' object has no attribute 'nancumprod'

### ISSUE THREAD

**Issue by LLplane** [abewley/sort#90]
hi,when run python sort.py,it can result the inf:

Traceback (most recent call last):
  File "sorttt.py", line 25, in <module>
    from skimage import io
  File "/home/lz/.local/lib/python2.7/site-packages/skimage/__init__.py", line 157, in <module>
    from .util.dtype import *
  File "/home/lz/.local/lib/python2.7/site-packages/skimage/util/__init__.py", line 6, in <module>
    from .apply_parallel import apply_parallel
  File "/home/lz/.local/lib/python2.7/site-packages/skimage/util/apply_parallel.py", line 8, in <module>
    import dask.array as da
  File "/home/lz/.local/lib/python2.7/site-packages/dask/array/__init__.py", line 5, in <module>
    from .core import (Array, block, concatenate, stack, from_array, store,
  File "/home/lz/.local/lib/python2.7/site-packages/dask/array/core.py", line 29, in <module>
    from . import chunk
  File "/home/lz/.local/lib/python2.7/site-packages/dask/array/chunk.py", line 73, in <module>
    nancumprod = npcompat.nancumprod
AttributeError: 'module' object has no attribute 'nancumprod'

**Comment by kunal8kabi** [comment]
Hello for this try install Sci-Kit image.

`pip install -U scikit-image`

or if you have Anaconda installed in your system

`conda install -c conda-forge scikit-image`
